version: "3.9"
services:
  crowdfooding-api:
    container_name: crowdfooding_api
    image: araujoyuri/crowdfooding_api
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crowdfooding_app
    ports:
      - "5432:5432"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
