"""create restaurants table

Revision ID: 376b0c7ae7bb
Revises: 103d7e4bd34a
Create Date: 2023-10-27 18:42:26.439165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '376b0c7ae7bb'
down_revision: Union[str, None] = '103d7e4bd34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('working_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint('unique_restaurants_id', 'restaurants', ['id'])
    op.add_column('products', sa.Column('restaurant_id', sa.UUID(), nullable=True))
    op.create_foreign_key('products_restaurant_id', 'products', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_restaurant_id', 'products', type_='foreignkey')
    op.drop_constraint('unique_restaurants_id', 'restaurants', type_='unique')
    op.drop_column('products', 'restaurant_id')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
