"""add image_url to products and restaurants

Revision ID: 8661827bab9a
Revises: 376b0c7ae7bb
Create Date: 2023-10-27 23:27:22.934227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8661827bab9a'
down_revision: Union[str, None] = '376b0c7ae7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'image_url')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
